### ISSUE TITLE
free IsClosed

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-packages/orb#44]
Is it possible to free the operation `IsClosed`?

I would  like to redeclare it as a property of constructible subsets of a topological space in the new packages `Locales` and `ZariskiFrames`.

Cf.

https://github.com/gap-packages/orb/blob/master/gap/orbits.gd#L37

**Comment by fingolfin** [comment]
I don't think that makes sense, for the very reason explained above that declaration:
```
# for backwards compatibility and convenience, declare an operation
# IsClosed which just returns IsClosedOrbit. This way, other packages
# can also use the term "IsClosed" for their purposes.
DeclareOperation( "IsClosed", [ IsOrbit ] );
```
The general approach to this type of name conflict in GAP is that each package declares a `IsClosedFOO` property, and then installs a method for the `IsClosed` operation that delegates to the actual method. That's how we do it for many other things, too.

**Comment by mohamed-barakat** [comment]
Your suggestion is indeed my current solution.

If I am not mistaking `IsOpen` is still free, so I declared it as a property. Are there guidelines against such a declaration?

**Comment by fingolfin** [comment]
There are no guidelines against such an operation, but experience tells that down the line, somebody will ask you to please change it to an operation, so that they can provide a method which aliases to their non-property ;-). But of course this also might never happen. So it's a matter of whether you want to be prepared for an eventuality that may or may not happen (and also have some symmetry between IsOpenFOO and IsClosedFOO); or whether you prefer to minimize the code you write now, and hope that you'll never have to change it (if you have to change it later, it may of course involve changing lots of packages which now rely on your IsClosed property...)

Anyway, closing this for now.

**Comment by fingolfin** [comment]
BTW, I notice that you have `IsOpen`, but also `IsOpenImmersion`; and other packages declare `IsOpenMathWriter`, `IsOpenSocket`; one certainly may wonder if GAP streams one day might get an `IsOpenStream` (we have `IsClosedStream` for now).
